Async/await configuration
ediguerrero/protractor-workshop-2018 pull request #5
Opened 2019-05-08 01:42 UTC by ediguerrero

![Captura de pantalla de 2019-05-07 20-25-15](https://user-images.githubusercontent.com/18091795/57343331-92ea0c80-7108-11e9-83a6-ff1d8720846b.png)

2019-05-08 02:54 UTC, yesid-lopez approved these changes

2019-05-08 13:21 UTC, sorregom requested changes

2019-05-08 13:21 UTC, sorregom commented on test/google.spec.ts
> +      await expect(browser.getTitle()).toEqual('Google');
cambia el await para que espere por la promesa de esta forma `expect( await ... `

2019-05-08 13:22 UTC, sorregom commented on test/google.spec.ts
> +      await expect(browser.getTitle()).toEqual('Google');
asi la espera es sólo mientras se completa la promesa del getTitle()

2019-05-09 19:22 UTC, sorregom approved these changes
OK

2019-05-09 19:27 UTC, merged